Upload Dome API nightly
ignitionrobotics/docs pull request #90
Opened 2020-09-29 19:09 UTC by chapulina

This can't be merged until all libraries have their release branches created.

Until then, the Dome API docs can be updated by re-triggering this run:

https://github.com/ignitionrobotics/docs/runs/1157160834?check_suite_focus=true

2020-10-01 16:52 UTC, chapulina commented
All branches have been created, this is ready to go

2020-10-05 21:06 UTC, caguero requested changes

2020-10-05 21:06 UTC, caguero commented on tools/Dockerfile.dome
> +RUN scripts/build_ign.sh ignitionrobotics ign-physics ign-physics2 y \
Should this be `ign-physics3`?

2020-10-05 21:09 UTC, chapulina commented on tools/Dockerfile.dome
> +RUN scripts/build_ign.sh ignitionrobotics ign-physics ign-physics2 y \
Nice catch 71d4585

2020-10-05 21:31 UTC, caguero approved these changes

2020-10-05 21:43 UTC, merged